version: '3.8'
services:
  nginx:
    ports:
      - 80:80
      - 443:443
  nodeapp:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - NODE_ENV=production
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}