version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  nodeapp: 
    build: .
    image: acupoflie/mocha-api
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo: 
    image: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: