version: '3.8'
services:
  nodeapp: 
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_USER=daupa
      - MONGO_PASSWORD=mypass
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daupa
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: